spring:
  data:
    redis:
      cache:
        host: ${spring.data.redis.cache.host}
        port: ${spring.data.redis.cache.port}
      auth:
        host: ${spring.data.redis.auth.host}
        port: ${spring.data.redis.auth.port}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope:
              - profile
              - email

  profiles:
    include: oauth


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# jwt
jwt:
  secret: ${jwt.secret}

# google login
#google:
#  auth:
#    url: https://oauth2.googleapis.com
#    scope: profile,
#  login:
#    url: https://accounts.google.com
#  redirect:
#    url: http://localhost:8080/api/members/login/redirect
#  client:
#    id: ${google.client.id}
#    secret: ${google.client.secret}



