spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    port: ${spring.redis.port}
    host: ${spring.redis.host}

# jwt
jwt:
  secret: ${jwt.secret}
