spring:
  data:
    redis:
      cache:
        host: ${spring.data.redis.cache.host}
        port: ${spring.data.redis.cache.port}
      auth:
        host: ${spring.data.redis.auth.host}
        port: ${spring.data.redis.auth.port}


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# jwt
jwt:
  secret: ${jwt.secret}
